.github/actions/build/action.yml, .github/workflows/android_builds.yml, .github/workflows/ios_builds.yml, .github/workflows/linux_builds.yml, .github/workflows/macos_builds.yml, .github/workflows/web_builds.yml, .github/workflows/windows_builds.yml, .vscode/settings.json, README.md, bin/addons/godot-rapier2d/README.md, scripts/build-rapier.sh, scripts/build.sh, scripts/generate-api.sh, src/rapier2d-wrapper/includes/rapier2d_wrapper.h, src/rapier2d-wrapper/src/body.rs, src/rapier2d-wrapper/src/collider.rs, src/rapier2d-wrapper/src/physics_hooks.rs, src/rapier2d-wrapper/src/physics_world.rs, src/spaces/rapier_space_2d.cpp, src/spaces/rapier_space_2d.h
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/8
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/1
=> Fix impulse local center. Also implement one way direction for rigidbodies.

README.md, src/bodies/rapier_body_2d.cpp, src/bodies/rapier_body_2d.h, src/bodies/rapier_collision_object_2d.cpp, src/rapier2d-wrapper/includes/rapier2d_wrapper.h, src/rapier2d-wrapper/src/collider.rs, src/rapier2d-wrapper/src/query.rs, src/rapier2d-wrapper/src/shape.rs, src/rapier2d-wrapper/src/vector.rs, src/rapier_include.h, src/servers/rapier_body_utils_2d.cpp, src/servers/rapier_physics_server_2d.cpp, src/spaces/rapier_direct_space_state_2d.cpp, src/spaces/rapier_direct_space_state_2d.h, src/spaces/rapier_space_2d.cpp
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/15
=> Shape Cast Node doesn't work

.github/actions/build/action.yml, .github/workflows/android_builds.yml, .github/workflows/ios_builds.yml, .github/workflows/linux_builds.yml, .github/workflows/macos_builds.yml, .github/workflows/runner.yml, .github/workflows/web_builds.yml, .github/workflows/windows_builds.yml, Godot-rapier-2d/How To Install.tscn, README.md, SConstruct, bin/addons/godot-rapier2d/godot-rapier2d.gdextension, src/rapier2d-wrapper/Cargo.toml, src/rapier2d-wrapper/src/physics_hooks.rs, src/servers/rapier_body_utils_2d.cpp, src/servers/rapier_physics_server_2d.cpp, src/spaces/rapier_space_2d.cpp
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/19
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/18
=> Add missing builds for platforms

README.md, src/rapier2d-wrapper/includes/rapier2d_wrapper.h, src/rapier2d-wrapper/src/physics_hooks.rs, src/servers/rapier_body_utils_2d.cpp, src/servers/rapier_body_utils_2d.h, src/servers/rapier_physics_server_2d.cpp, src/shapes/rapier_separation_ray_shape_2d.h, src/shapes/rapier_shape_2d.h, src/spaces/rapier_space_2d.cpp
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/10
-
=> Fix character body one way direction

README.md, src/bodies/rapier_body_2d.cpp, src/bodies/rapier_body_2d.h, src/servers/rapier_body_utils_2d.cpp, src/spaces/rapier_space_2d.cpp
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/11
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/2
=> Add static body conveyer belt

src/bodies/rapier_collision_object_2d.h, src/spaces/rapier_space_2d.cpp
-Fixes https://github.com/appsinacup/godot-rapier-2d/issues/26
=> Fix crash in modify contacts

bin/addons/godot-rapier2d/Fluid2DCircle.gd, bin/addons/godot-rapier2d/Fluid2DRectangle.gd, bin/addons/godot-rapier2d/Fluid2DRenderer.gd, src/fluids/fluid_2d.cpp, src/fluids/fluid_2d.h, src/register_types.cpp, src/servers/rapier_project_settings.cpp, src/servers/rapier_project_settings.h
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/62
=> Fix crash. Update fluid debug rendering to be internal.

README.md, bin/addons/godot-rapier2d/Fluid2DRenderer.gd, bin/addons/godot-rapier2d/fluid_multi_mesh.tres, bin/samples/godot-rapier2d/CharacterBody2D.gd, bin/samples/godot-rapier2d/Faucet2D.gd, bin/samples/godot-rapier2d/test_fluid.tscn, godot-rapier.code-workspace, scripts/build.sh, src/bodies/rapier_collision_object_2d.cpp, src/fluids/fluid_2d.cpp, src/fluids/fluid_2d.h, src/fluids/rapier_fluid_2d.cpp, src/fluids/rapier_fluid_2d.h, src/joints/rapier_pin_joint_2d.cpp, src/rapier2d-wrapper/includes/rapier2d_wrapper.h, src/rapier2d-wrapper/src/fluid.rs, src/servers/rapier_physics_server_2d.cpp, src/servers/rapier_physics_server_2d.h
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/68
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/67
=> Add particle lifetime. Fix shape disabled warning.

src/rapier2d-wrapper/Cargo.toml, src/rapier2d-wrapper/src/collider.rs
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/88
=> Fix halfspace hang

src/bodies/rapier_collision_object_2d.cpp, src/shapes/rapier_shape_2d.h
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/90
=> fix shape not updating

src/bodies/rapier_collision_object_2d.cpp
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/93
=> Fix parent scale not getting applied correctly

src/bodies/rapier_collision_object_2d.cpp
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/92
=> Fix destroy shape race condition

src/rapier2d-wrapper/Cargo.toml, src/rapier2d-wrapper/src/convert.rs, src/rapier2d-wrapper/src/joint.rs, src/rapier2d-wrapper/src/query.rs
- Fixes https://github.com/appsinacup/godot-rapier-2d/issues/96
=> Fix build issue in build after rapier 0.19. Also fix pin joint rotation issue.

.cargo/config.toml, .github/actions/build/action.yml, .github/workflows/linux_builds.yml, .github/workflows/runner.yml, .github/workflows/web_builds.yml, .github/workflows/windows_builds.yml, Cargo.lock, Cargo.toml, bin2d/addons/godot-rapier2d/godot-rapier2d.gdextension, bin2d/project.godot, bin3d/addons/godot-rapier3d/godot-rapier3d.gdextension, scripts/build-web.sh
Doesn't fix that issue but just enables web builds. They are still broken and needs investigation, but enabling the pipeline in meantime.
=> Re enable web build

.github/workflows/windows_builds.yml, .gitignore, Cargo.toml, README.md, bin2d/area_2d.gd, bin2d/rigid_body_2d_3.gd, bin2d/test.gd, bin2d/test.tscn, src/bodies/rapier_area.rs, src/bodies/rapier_body.rs, src/bodies/rapier_collision_object.rs, src/bodies/rapier_collision_object_impl.rs, src/rapier_wrapper/collider.rs, src/rapier_wrapper/query.rs, src/servers/rapier_physics_server_impl.rs, src/spaces/rapier_direct_space_state_impl.rs, src/spaces/rapier_space_body_helper.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/113
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/107
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/106
=> Small update for areas. Also look into reenabling character body. Also small fix for shapes removed.

src/rapier_wrapper/query.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/123
=> fix raycast not sorting results

README.md, src/bodies/rapier_collision_object.rs, src/joints/rapier_damped_spring_joint_2d.rs, src/joints/rapier_groove_joint_2d.rs, src/joints/rapier_joint.rs, src/joints/rapier_pin_joint_2d.rs, src/rapier_wrapper/body.rs, src/rapier_wrapper/physics_world.rs, src/servers/rapier_physics_server_extra.rs, src/servers/rapier_physics_server_impl.rs, src/spaces/rapier_space.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/134
=> fix determinism locally by deleting whole state if physics world is empty

CHANGELOG.md, bin2d/test.tscn, src/bodies/rapier_body.rs, src/fluids/fluid_impl.rs, src/rapier_wrapper/fluid.rs, src/rapier_wrapper/query.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/166
=> fix linear/angular damp

Cargo.lock, Cargo.toml
Should fix shapes getting stuck
=> Parry convergence issues custom branch.

src/bodies/rapier_area.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/169
=> Fix area event issues

src/shapes/rapier_segment_shape_2d.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/181
=> fix segment shape

src/bodies/rapier_area.rs, src/bodies/rapier_body.rs, src/bodies/rapier_collision_object.rs, src/bodies/rapier_collision_object_impl.rs, src/rapier_wrapper/physics_world.rs, src/rapier_wrapper/user_data.rs, src/spaces/rapier_space.rs, src/spaces/rapier_space_callbacks.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/186
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/185
=> fix areas removed issue

Cargo.lock, Cargo.toml, src/rapier_wrapper/collider.rs, src/rapier_wrapper/query.rs, src/servers/rapier_project_settings.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/195
=> add experimental threads for now to fix wrong thread access

README.md
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/194
=> Update README.md with limitations

src/bodies/rapier_body.rs, src/rapier_wrapper/body.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/232
=> fix inertia not being calculated correctly.

THIRDPARTY.txt, src/shapes/rapier_world_boundary_shape.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/238
=> fix world boundary shape distance

Cargo.lock, src/rapier_wrapper/physics_world.rs, src/rapier_wrapper/shape.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/248
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/269
=> Fix point warning and raycast slowdown

Cargo.lock, Cargo.toml, src/rapier_wrapper/query.rs
- Fixes: https://github.com/appsinacup/godot-rapier-physics/issues/262
Before the points reported were in local space instead of global space.
=> fix case where contacts are missed

src/rapier_wrapper/query.rs, src/spaces/rapier_direct_space_state_impl.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/193
=> finally implement unsafe fraction for all.

src/bodies/rapier_body.rs, src/rapier_wrapper/body.rs, src/rapier_wrapper/collider.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/291
=> fix layer and mask reseting friction

src/rapier_wrapper/physics_world.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/290
=> fix removed collider event not triggering

CONTRIBUTING.md
Small PR - adjusts the broken links in the `CONTRIBUTING.md` file.
=> Update godot source file references

CHANGELOG.md, Cargo.lock, Cargo.toml, bin2d/addons/godot-rapier2d/plugin.info.cfg, bin3d/addons/godot-rapier3d/plugin.info.cfg, src/spaces/rapier_space_body_helper.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/324
=> fix characterbody one way dir bug

src/shapes/rapier_circle_shape.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/315
=> Allow circles to have 0 radius

Cargo.lock, Cargo.toml, src/fluids/rapier_fluid.rs, src/rapier_wrapper/collider.rs, src/rapier_wrapper/fluid.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/281
=> fix liquid phantom collisions

src/rapier_wrapper/query.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/307
=> Fix shape contact when velocity is 0

src/bodies/rapier_collision_object_base.rs, src/rapier_wrapper/body.rs, src/rapier_wrapper/collider.rs
Add support for direct PhysicsServer API access by correctly initializing transform positions.
The change in body.rs might not be necessary, I think I might have been trying to fix something else.
=> Add support for direct PhysicsServer API access

src/bodies/rapier_body.rs
- Fixes https://github.com/appsinacup/godot-rapier-physics/issues/363
=> fix typo in agular damping mode
